version: '3.8'

services:
  pdf-extractor:
    build: .
    container_name: pdf-text-extractor
    ports:
      - "5001:5000"
    environment:
      # タイムゾーン設定
      - TZ=Asia/Tokyo
    # ヘルスチェック
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s